name: Daily Meal Notifier

on:
  schedule:
    - cron: "0 20 * * *"  # Runs daily at 12 PM PST (20:00 UTC)
  workflow_dispatch:       # Allows manual triggering via GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily script
        run: python daily_meal_notifier.py
